version: 1

bootstrap_servers:
  internal: kafka:29092
  external: localhost:9092

defaults:
  partitions: 3    
  replication_factor: 1    # Chạy trên local 

topics:
  raw_network_events:
    name: raw.ue.log.line.
    producer: log-producer
    consumers:
      - flink-preprocess

  processed_network_events:
    name: processed.ue.log.line.
    producer: flink-preprocess
    consumers:
      - inference-service

  anomaly_predictions:
    name: anomaly.prediction.
    producer: inference-service
    consumers:
      - nwdaf-adapter